name: daina
favicon: null
layout_spectrum: 0.7054717990104109
typography_spectrum: 0.9671919911634177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4465796451549977
  lightness: 0.6073649995960295
  saturation: 0.4291423649992794
  rhythmicContrast: 0.8113840438891202
purpose: []
