name: daina
favicon: null
layout_spectrum: 0
typography_spectrum: 0.41766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b38a1'
    - '#cf73b6'
    - '#ffffff'
    - '#4e0056'
    - '#caafd9'
  brandStrength: 0.375
  lightness: 0.6073649995960295
  saturation: 0.625
  rhythmicContrast: 0.8113840438891202
purpose: []
